config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :users
  

  root 'homes#index'
  resources :homes
  resources :items
  resources :sales

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :sale
	validates_presence_of :item_name
	validates_presence_of :barcode
	validates_presence_of :quantity
	validates_presence_of :cost_price
	validates_presence_of :retail_price
	validates_presence_of :date_delivered
	validates_numericality_of :cost_price, :message=>"must be numeric"
	validates_numericality_of :retail_price, :message=>"must be numeric"

	include PgSearch
	multisearchable :against => [:item_name, :barcode]


  # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
   Item.where("item_name ilike ? or barcode like ?", "%#{query}%", "%#{query}%")
  end
end

app/models/sale.rb
class Sale < ActiveRecord::Base

	include PgSearch
	multisearchable :against => [:item_name, :barcode]

	def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
   Item.where("item_name ilike ? or barcode like ?", "%#{query}%", "%#{query}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  layout 'admin_lte_2'

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    if params[:search]
      @items = Item.search(params[:search]).order("created_at DESC")
    else
      @items = Item.order("created_at DESC")
    end 
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:item_name, :description, :barcode, :cost_price, :retail_price, :date_delivered, :date_of_expiry, :quantity)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
    if params[:search]
      @items = Item.search(params[:search]).order("created_at DESC")
    else
      @items = Item.order("created_at DESC")
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:customer_name, :item_name, :description, :barcode, :cost_price, :retail_price, :date_delivered, :date_of_expiry, :quantity, :sales_person, :date_sold)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/homes/index.html.erb
<div class="box box-primary">
        <!-- Content Header (Page header) -->
        <section class="box-header">
        </section>

        <!-- Main content -->
        <section class="box-body">
          <!-- Small boxes (Stat box) -->
          <div class="row">
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-aqua">
                <div class="inner">
                  <h2>Sale</h2>
                </div>
                <div class="icon">
                  <i class="fa fa-shopping-cart"></i>
                </div>
                <a href="/sales" class="small-box-footer">Sell Item <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-green">
                <div class="inner">
                  <h2>Items<sup style="font-size: 20px"></sup></h2>
                  
                </div>
                <div class="icon">
                  <i class="fa fa-list"></i>
                </div>
                <a href="/items" class="small-box-footer">Item List <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-yellow">
                <div class="inner">
                  <h2>Inventory</h2>
                </div>
                <div class="icon">
                  <i class="ion ion-person-add"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-red">
                <div class="inner">
                  <h2>Patronage</h2>
                </div>
                <div class="icon">
                  <i class="ion ion-pie-graph"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
          </div><!-- /.row -->
          <!-- Main row -->
        </section><!-- /.content -->
</div><!-- /.content-wrapper -->

app/views/items/_form.html.erb
<%= form_for(@item, html: { class: "form-horizontal", role: "form" }) do |f| %>
  
  <% if @item.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h4>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :item_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :item_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :barcode, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :barcode, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cost_price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cost_price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :retail_price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :retail_price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_delivered, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :date_delivered, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_of_expiry, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :date_of_expiry, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantity, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :quantity, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/items/_search.html.erb
    <div class="col-sm-3" style="float:right; padding-bottom:5px">
    <!-- When submit the form, the view rendered will be the index view of our articles resource -->
    <%= form_tag(items_path, :method => "get", id: "search-form") do %>
      <div class="input-group input-group-sm">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Items" %>
        <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
        <span class="input-group-btn">
          <button class="btn btn-info btn-flat" type="submit">Go!</button>
        </span>
      </div>
      <%end%>
    </div>

app/views/items/edit.html.erb
<div class="box box-primary">
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @item, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Edit Item</h1>
</div>

<%= render 'form' %>
</div>

app/views/items/index.html.erb
<div class="box box-primary">
<div class="page-header">
  <%= link_to new_item_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Add Item

  <% end %>
  <h1>List of Items</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover" id="example1">
    <thead>
      <tr>
            <th>Item name</th>
            <th>Description</th>
            <th>Barcode</th>
            <th>Cost Price</th>
            <th>Retail Price</th>
            <th>Date Delivered</th>
            <th>Date of Expiry</th>
            <th>Quantity</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @items) do |item| %>
            <td><%= item.item_name %></td>
            <td><%= item.description %></td>
            <td><%= item.barcode %></td>
            <td><%= item.cost_price %></td>
            <td><%= item.retail_price %></td>
            <td><%= item.date_delivered %></td>
            <td><%= item.date_of_expiry %></td>
            <td><%= item.quantity %></td>
            <td><%= link_to 'Show', item %> |
        <%= link_to 'Edit', edit_item_path(item) %> |
        <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/items/new.html.erb
<div class="box box-primary">
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Add Item</h1>
</div>
<%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="box box-primary">
<div class="page-header">
  <%= link_to items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_item_path(@item), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Item Info</h1>
</div>

<dl class="dl-horizontal">
  <dt>Item name:</dt>
  <dd><%= @item.item_name %></dd>

  <dt>Description:</dt>
  <dd><%= @item.description %></dd>

  <dt>Barcode:</dt>
  <dd><%= @item.barcode %></dd>

  <dt>Cost price:</dt>
  <dd><%= @item.cost_price %></dd>

  <dt>Retail price:</dt>
  <dd><%= @item.retail_price %></dd>

  <dt>Date delivered:</dt>
  <dd><%= @item.date_delivered %></dd>

  <dt>Date of expiry:</dt>
  <dd><%= @item.date_of_expiry %></dd>

  <dt>Quantity:</dt>
  <dd><%= @item.quantity %></dd>

</dl>
</div>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Navigation</li>
        <!-- Optionally, you can add icons to the links -->
      <li class="active"></i><%= link_to 'Dashboard', homes_path %></li>

      <li class="treeview">
        <a href="#"><i class='fa fa-shopping-cart'></i> <span>Sales</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><%= link_to 'List of Sold Items', sales_path %></li>
          <li><%= link_to 'Sell Item', new_sale_path %></li>
        </ul>
      </li>

      <li class="treeview">
        <a href="#"><i class='fa fa-th-list'></i> <span>Items</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><%= link_to 'List of Items', items_path %></li>
          <li><%= link_to 'Add Item', new_item_path %></li>
        </ul>
      </li>

      <li class="treeview">
        <a href="#"><i class='fa fa-th-list'></i> <span>Inventory</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><%= link_to 'List of Items', items_path %></li>
          <li><%= link_to 'Add Item', new_item_path %></li>
        </ul>
      </li>

      <li class="treeview">
        <a href="#"><i class='fa fa-th-list'></i> <span>Patronage</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><%= link_to 'List of Items', items_path %></li>
          <li><%= link_to 'Add Item', new_item_path %></li>
        </ul>
      </li>

    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>KCMDC Store</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_lte_2_header' %>

    <%= render partial: 'layouts/admin_lte_2_sidebar' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
     <section class="content-header" style="padding-top: 0">
        <h1>
          KCMDC
          <small> Store</small>
        </h1>
        <ol class="breadcrumb">
          <li><i class="fa fa-dashboard"></i><%= link_to 'Dashboard', homes_path %></li>
          <li class="active">Here</li>
        </ol>
      </section>


      <!-- Main content -->
      <section class="content">
        <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= yield %>
      </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->
      <div class="pull-right hidden-xs">
        Version 1.0
      </div>
      <!-- Default to the left -->
      <strong>Copyright &copy; 2015 <a href="https://www.facebook.com/kiphodandevs">Kiphodan Developers</a>.</strong> All rights reserved.
    </footer>

    

      <div class="control-sidebar-bg" style="position: fixed; height: auto;"></div>

  </div><!-- ./wrapper -->

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>KCMDC Store | Log in</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>KCMDC </b>Store</a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Please Sign in!</p>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :email, class: 'form-control', autofocus: true %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              &nbsp&nbsp&nbsp&nbsp&nbsp<input type="checkbox">Remember Me
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit 'Log in', class: 'btn btn-primary btn-block btn-flat' %>

        </div><!-- /.col -->
      </div>

    <% end %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/sales/_index.html.erb
<div class="box box-primary">
<div class="page-header">
  <%= link_to new_item_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Add Item

  <% end %>
  <h1>List of Items For Sale</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover" id="example1">
    <thead>
      <tr>
            <th>Item name</th>
            <th>Description</th>
            <th>Barcode</th>
            <th>Cost Price</th>
            <th>Retail Price</th>
            <th>Date Delivered</th>
            <th>Date of Expiry</th>
            <th>Quantity</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @items) do |item| %>
            <td><%= item.item_name %></td>
            <td><%= item.description %></td>
            <td><%= item.barcode %></td>
            <td><%= item.cost_price %></td>
            <td><%= item.retail_price %></td>
            <td><%= item.date_delivered %></td>
            <td><%= item.date_of_expiry %></td>
            <td><%= item.quantity %></td>
            <td><%= link_to 'Show', item %> |
        <%= link_to 'Edit', edit_item_path(item) %> |
        <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/sales/_search.html.erb
 <div class="col-sm-3" style="float:right; padding-bottom:5px">
    <!-- When submit the form, the view rendered will be the index view of our articles resource -->
    <%= form_tag(sales_path, :method => "get", id: "search-form") do %>
      <div class="input-group input-group-sm">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Items" %>
        <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
        <span class="input-group-btn">
          <button class="btn btn-info btn-flat" type="submit">Go!</button>
        </span>
      </div>
      <%end%>
    </div>

app/views/sales/edit.html.erb
<div class="box box-primary">
<div class="page-header">
  <%= link_to sales_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @sale, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing sale</h1>
</div>

<%= render 'form' %>
</div>

app/views/sales/index.html.erb
<div class="box box-primary">
<div class="page-header">
  <%= link_to new_sale_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Sale
  <% end %>
  <h1>List of sales</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover" id="example1">
    <thead>
      <tr>
            <th>Customer name</th>
            <th>Item name</th>
            <th>Description</th>
            <th>Barcode</th>
            <th>Cost price</th>
            <th>Retail price</th>
            <th>Date delivered</th>
            <th>Date of expiry</th>
            <th>Quantity</th>
            <th>Sales person</th>
            <th>Date sold</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @sales) do |sale| %>
            <td><%= sale.customer_name %></td>
            <td><%= sale.item_name %></td>
            <td><%= sale.description %></td>
            <td><%= sale.barcode %></td>
            <td><%= sale.cost_price %></td>
            <td><%= sale.retail_price %></td>
            <td><%= sale.date_delivered %></td>
            <td><%= sale.date_of_expiry %></td>
            <td><%= sale.quantity %></td>
            <td><%= sale.sales_person %></td>
            <td><%= sale.date_sold %></td>
            <td><%= link_to 'Show', sale %> |
              <%= link_to 'Edit', edit_sale_path(sale)%> |
              <%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/sales/new.html.erb
<div class="box box-primary">
<div class="page-header">
  <%= link_to sales_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Sale</h1>
</div>
<div class="box-body">
<%= render 'search' %>
</div>
<%= render 'form' %>
</div>

app/views/sales/show.html.erb
<div class="box box-primary">
<div class="page-header">
  <%= link_to sales_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_sale_path(@sale), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Sale</h1>
</div>

<dl class="dl-horizontal">
  <dt>Customer name:</dt>
  <dd><%= @sale.customer_name %></dd>

  <dt>Item name:</dt>
  <dd><%= @sale.item_name %></dd>

  <dt>Description:</dt>
  <dd><%= @sale.description %></dd>

  <dt>Barcode:</dt>
  <dd><%= @sale.barcode %></dd>

  <dt>Cost price:</dt>
  <dd><%= @sale.cost_price %></dd>

  <dt>Retail price:</dt>
  <dd><%= @sale.retail_price %></dd>

  <dt>Date delivered:</dt>
  <dd><%= @sale.date_delivered %></dd>

  <dt>Date of expiry:</dt>
  <dd><%= @sale.date_of_expiry %></dd>

  <dt>Quantity:</dt>
  <dd><%= @sale.quantity %></dd>

  <dt>Sales person:</dt>
  <dd><%= @sale.sales_person %></dd>

  <dt>Date sold:</dt>
  <dd><%= @sale.date_sold %></dd>

</dl>
</div>